# Generated by Django 5.0.4 on 2024-05-03 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_rename_attachement_projectfile_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
